package io.github.codetoil.litlaunch.api.library_api;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : /workspaces/LitLaunch/litlaunch-library-api/src/main/c/litlaunch-library-api.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("litlaunch-library-api") 
public class LitlaunchPlugin extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public int size() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public LitlaunchPlugin size(int size) {
		this.io.setIntField(this, 0, size);
		return this;
	}
	/** C type : ISoftware* */
	@Field(1) 
	public Pointer<Software > info() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : ISoftware* */
	@Field(1) 
	public LitlaunchPlugin info(Pointer<Software > info) {
		this.io.setPointerField(this, 1, info);
		return this;
	}
	/** C type : ILibrary* */
	@Field(2) 
	public Pointer<LitlaunchLibrary > requiredLibrary() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : ILibrary* */
	@Field(2) 
	public LitlaunchPlugin requiredLibrary(Pointer<LitlaunchLibrary > requiredLibrary) {
		this.io.setPointerField(this, 2, requiredLibrary);
		return this;
	}
	public LitlaunchPlugin(String name, String version, LitlaunchLibrary library) {
		this(LitlaunchLibraryApiLibrary.createPluginStruct(
			Pointer.pointerToCString(name),
			Pointer.pointerToCString(version),
			Pointer.getPointer(library)));
	}
	public LitlaunchPlugin(Pointer<LitlaunchPlugin> pointer) {
		super(pointer);
	}
}
