# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build_debug
on: [pull_request, push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: 'ubuntu-22.04'
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Configure CMake (First Time)
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build litlaunch-library-api
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target litlaunch-library-api
      - name: Configure CMake (Second Time)
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build litlaunch-library-api-exe-test1
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target litlaunch-library-api-exe-test1
      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: |
            build/litlaunch-library-api/liblitlaunch-library-api.a
            build/litlaunch-library-api/test/litlaunch-library-api-exe-test1
            
